lab04/lab04/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('votacion/', include('votaciones.urls')),
    path('admin/', admin.site.urls),
]

lab04/votaciones/urls.py
from django.urls import URLPattern, path

from . import views

app_name = 'votaciones'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id_region>/', views.list_candidatos, name="list_candidatos"),
    path('<int:id_candidato>/detalle_candidato', views.detalle_candidato, name="detalle_candidato"),
]

lab04/votaciones/models.py
from django.db import models
from django.forms import CharField

# Create your models here.
class Region(models.Model):
    nombre_reg = models.CharField(max_length=20)

class Candidato(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    nombre_cand = models.CharField(max_length=20)
    apellido_cand = models.CharField(max_length=20)
    edad_cand = models.IntegerField(max_length=2)
    origen_cand = models.CharField(max_length=15)
    fecha_nacimiento = models.DateTimeField('date of birth')
    partido = models.CharField(max_length=15)

lab04/votaciones/views.py
from multiprocessing import context
from select import select
from django.shortcuts import get_object_or_404, render
from .models import Region, Candidato
# Create your views here.

def index(request):
    lista_regiones = Region.objects.all()
    context={
        'lista_regiones': lista_regiones
    }
    return render(request, 'votaciones/index.html', context)

def list_candidatos(request, id_region):
    #lista_candidatos = Candidato.objects.filter(region_id=id_region)
    lista_candidatos = get_object_or_404(Region,pk=id_region)
    context={
        'lista_candidatos': lista_candidatos
    }
    return render(request, 'votaciones/candidatos.html', context)

def detalle_candidato(request, id_candidato):
    detalles_candidato = get_object_or_404(Candidato, pk=id_candidato)
    return render(request, 'votaciones/detalle_candidato.html',{'detalles_candidato':detalles_candidato})

lab04/votaciones/templates/votaciones/candidatos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candidatos Postulantes</title>
</head>
<body class="bg-info">
    <br><br>
<div class="container py-5 bg-light">
    <h1 class="text-center">CANDIDATOS POSTULANTES DE LA REGION {{ lista_candidatos.nombre_reg }}</h1><hr>
    {% if lista_candidatos %}
        <table class="table table-hover">
                <tr class="table-info text-center">
                    <td>NOMBRE DEL CANDIDATO</td>
                    <td>APELLIDO DEL CANDIDATO</td>
                    <td>PARTIDO POLITICO</td>
                </tr>
            {% for region in lista_candidatos.candidato_set.all %}
                <tr>
                    <td><a href="{% url 'votaciones:detalle_candidato' region.id %}">{{ region.nombre_cand }}</a></td>
                    <td>{{ region.apellido_cand }}</td>
                    <td>{{ region.partido }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No se encuentran resultados</p>
    {% endif %}
    <div>
        <a href="{% url 'votaciones:index' %}"><input type="button" value="Volver" class="btn btn-success"></a>
    </div>
</div>
</body>
</html>

lab04/votaciones/templates/votaciones/detalle_candidato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Informacion</title>
</head>
<body class="bg-info">
    <br><br>
    <div class="container py-5 bg-light">
        <h1 class="text-center">DATOS DEL CANDIDATO</h1><br><hr>
    {% if detalles_candidato %}
        <table class="table">
            <tr class="table-primary text-center">
                <td>NOMBRE</td>
                <td>APELLIDO</td>
                <td>EDAD</td>
                <td>LUGAR DE ORIGEN</td>
                <td>FECHA DE NACIMIENTO</td>
                <td>PARTIDO POLITICO</td> 
            </tr>
            <tr>
                <td>{{ detalles_candidato.nombre_cand }}</td>
                <td>{{ detalles_candidato.apellido_cand }}</td>
                <td>{{ detalles_candidato.edad_cand }}</td>
                <td>{{ detalles_candidato.origen_cand }}</td>
                <td>{{ detalles_candidato.fecha_nacimiento }}</td>
                <td>{{ detalles_candidato.partido }}</td>
            </tr>
        </table>
    {% else %}
        <p>No se encontraron datos</p>
    {% endif %}
        <div>
            <a href="{% url 'votaciones:index' %}"><input type="button" value="Volver" class="btn btn-success"></a>
        </div>
    </div>
</body>
</html>

lab04/votaciones/templates/votaciones/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Regiones</title>
</head>
<body class="bg-info">
    <br>
<div class="container text-center py-5 d-grid gap-2 col-4 mx-auto bg-light">
    
    <div class="bg-primary">
        <hr>
        <h1>REGIONES</h1><hr>
    </div>
    {%if lista_regiones %}
            {% for region in lista_regiones %}
                <div class="container">
                    <a href="/votacion/{{ region.id }}">{{ region.nombre_reg }}</a><br>
                </div><br>
            {% endfor %}
    {% else %}
        <p>No hay registro alguno</p>
    {% endif %}
</div>
</body>
</html>